### ISSUE TITLE
com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzas;

### ISSUE THREAD

**Issue by francocorreasosa** [OneSignal/react-native-onesignal#20]
I got this error after linking the library with the Android project

```
Unknown source file : UNEXPECTED TOP-LEVEL EXCEPTION:
Unknown source file : com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzas;
Unknown source file :   at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
Unknown source file :   at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
Unknown source file :   at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
Unknown source file :   at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
Unknown source file :   at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
Unknown source file :   at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
Unknown source file :   at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
Unknown source file :   at com.android.dx.command.dexer.Main.run(Main.java:277)
Unknown source file :   at com.android.dx.command.dexer.Main.main(Main.java:245)
Unknown source file :   at com.android.dx.command.Main.main(Main.java:106)
```

**Comment by jkasten2** [comment]
### Update 2018-11-07
This looks to be conflict with another plugin including a different interdependency of the Google Play services library.  I recommend using the [OneSignal-Gradle-Plugin](https://github.com/OneSignal/OneSignal-Gradle-Plugin) as using `+` isn't recommended as it could result in upgrading to an incompatible version without warning. Using `+` versions also isn't recommend by Google, and it will not work for all versions of OneSignal or all other plugins.

**Setup**
Open your app/build.gradle (Module: app) file, add the following to the very top.
```gradle
buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/'}
    }
    dependencies {
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.12.1, 0.99.99]'
    }
}
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
```

---

<details>
  <summary>Original Reply: 2016-04-22</summary>
  This looks to be conflict with another plugin your using. You can try to update the [android/build.gradle](https://github.com/geektimecoil/react-native-onesignal/blob/430aab6221b6fcc0785275c7a1a54f25f3b424c7/android/build.gradle#L37-L39) to use the latest version of `com.google.android.gms` by replacing the version with +.
Line

```gradle
 compile 'com.google.android.gms:play-services-gcm:+'
 compile 'com.google.android.gms:play-services-analytics:+'
 compile 'com.google.android.gms:play-services-location:+'
```

If this results in the same error you will need to check the other plugins as well for the same thing.
</details>

**Comment by avishayil** [comment]
Thanks @jkasten2 .
@francocorreasosa Please report after trying the fix Josh suggested.

**Comment by BigPun86** [comment]
+1 worked for me!

**Comment by zsajjad** [comment]
Having same issue!

android/app/build.gradle

```
dependencies {
    compile project(':react-native-facebook-account-kit')
    compile fileTree(dir: "libs", include: ["*.jar"])
    compile "com.android.support:appcompat-v7:23.0.1"
    compile "com.google.android.gms:play-services-location:8.3.0"
    compile "com.facebook.react:react-native:+"
    compile("com.google.android.gms:play-services-analytics:8.3.0"){
      force = true
    }
    compile project(':react-native-onesignal')
    compile project(':react-native-google-analytics-bridge')
    compile project(":react-native-share")
    compile project(":react-native-vector-icons")
    compile project(':react-native-android-statusbar')
    compile project(":react-native-facebook-login")
    compile project(":react-native-google-signin")
    compile project(":react-native-image-picker")
}
```

**Comment by cesarvega** [comment]
My configurations looks different.
So where do you add it in my case 
 `

      dependencies {
	       def supportVer = "22.2.0";
	       if (project.hasProperty("supportVersion")) {
	      	supportVer = supportVersion
	       }

             compile "com.android.support:support-v4:$supportVer"
            compile "com.android.support:appcompat-v7:$supportVer"
	    debugCompile "com.android.support:design:$supportVer"

              // take all jars within the libs dir
	          compile fileTree(dir: "$projectDir/libs", include: ["**/*.jar"])
          }

            ////////////////////////////////////////////////////////////////////////////////////
           ///////////////////////////// CONFIGURATION PHASE //////////////////////////////////
            ////////////////////////////////////////////////////////////////////////////////////`

**Comment by isacoskun** [comment]
Hello, I have such a problem. How could I solve it?

https://stackoverflow.com/questions/48630943/when-i-want-to-create-apk-in-the-android-studio-i-get-this-error

**Comment by policz** [comment]
This is the issue,  when i run react-native run-android after configuring firebase to my react-native 
project. And also please find the attachments below.

[android-app-build.gradle.txt](https://github.com/geektimecoil/react-native-onesignal/files/1845043/android-app-build.gradle.txt)
[android-build.gradle.txt](https://github.com/geektimecoil/react-native-onesignal/files/1845044/android-build.gradle.txt)
[mainApplication.java.txt](https://github.com/geektimecoil/react-native-onesignal/files/1845045/mainApplication.java.txt)
[settings-gradle.txt](https://github.com/geektimecoil/react-native-onesignal/files/1845046/settings-gradle.txt)





Dex: Error converting bytecode to dex:
Cause: com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzfkt;
    UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzfkt;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:591)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:546)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:528)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:164)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:188)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:504)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
        at com.android.dx.command.dexer.Main.run(Main.java:277)
        at com.android.dx.command.dexer.Main.main(Main.java:245)
        at com.android.dx.command.Main.main(Main.java:106)

:app:transformClassesWithDexForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Error while executing java process with main class com.android.dx.command.Main with arguments {--dex --num-threads=4 --output C:\Users\eakhmas\src\ehs-mobile-app\android\app\build\intermediates\transforms\dex\debug\folders\1000\1f\main C:\Users\eakhmas\src\ehs-mobile-app\android\app\build\intermediates\pre-dexed\debug\classes_0558014b1a2499fa62ae2e179d92eedb25a2db34.jar C:\Users\eakhmas\src\ehs-mobile-app\android\app\build\intermediates\pre-dexed\debug\debug_157f80f326c56e04a0ba82aaeee654fcce67b9e2.jar C:\Users\eakhmas\src\ehs-mobile-app\android\app\build\intermediates\pre-dexed\debug\classes_c4d3b679ddf1f7a1b6dd160881c6cd4f3e963961.jar C:\Users\eakhmas\src\ehs-mobile-app\android\app\build\intermediates\pre-dexed\debug\classes_883586b33f8bf3c18dbfbb2d9ac46163b710db23.jar C:\Users\eakhmas\src\ehs-mobile-app\android\app\build\intermediates\pre-dexed\debug\bolts-tasks-1.4.0_79ae474447df465463046cf669d3dcff3fb6bd0c.jar C:\Users\eakhmas\src\ehs-mobile-app\android\app\build\intermediates\pre-dexed\debug\classes_dc55cc6428c7ed95bd4d65e20e8fe3b182c81144.jar C:\Users\eakhmas\src\ehs-mobile-app\android\app\build\intermediates\pre-dexed\debug\classes_85cd5714ecff6e2c64676ff08fd3cc32ecd51dd5.jar C:\Users\eakhmas\src\ehs-mobile-app\android\app\build\intermediates\pre-dexed\debug\classes_7248c61a51477b5b1278913e923ab24b9d918577.jar C:\Users\eakhmas\src\ehs-mobile-app\android\app\build\intermediates\pre-dexed\debug\classes_f9cec181f215a2062f22de310377a4adcb0eb68d.jar C:\Users\eakhmas\src\ehs-mobile-app\android\app\build\intermediates\pre-dexed\debug\javax.inject-1_21946a94be40da79aab1de46e61c1d97e30c5d38.jar C:\Users\eakhmas\src\ehs-mobile-app\android\app\build\intermediates\pre-dexed\debug\classes_8c2e65d49efd954193fd8f3d17b0daa3a9ccb614.jar C:\Users\eakhmas\src\ehs-mobile-app\android\app\build\intermediates\pre-dexed\debug\classes_6a45ee2e6ed53420648ebbf0a53dd95d5bc57353.jar C:\Users\eakhmas\src\ehs-mobile-app\android\app\build\intermediates\pre-dexed\debug\classes_6142895da50162f27d2d0cc624c720ea1e195276.jar C:\Users\eakhmas\src\ehs-mobile-app\android\app\build\intermediates\pre-dexed\debug\infer-annotations-4.0_f815966bc82744c5990edeb11acdadf1edd137ea.jar C:\Users\eakhmas\src\ehs-mobile-app\android\app\build\intermediates\pre-dexed\debug\classes_2c80bfc6a51f9dc06c9167301fc8d03ae9b65597.jar C:\Users\eakhmas\src\ehs-mobile-app\android\app\build\intermediates\pre-dexed\debug\classes_b0a30a3d75094aed0b8f5f2ff187d2ea420d1c2f.jar C:\Users\eakhmas\src\ehs-mobile-app\android\app\build\intermediates\pre-dexed\debug\classes_17a925ca4044eee6b88a24ecf7a26ca20414df4e.jar C:\Users\eakhmas\src\ehs-mobile-app\android\app\build\intermediates\pre-dexed\debug\classes_1b5670d63cafa1e95db68f9187d9e05d7590e607.jar C:\Users\eakhmas\src\ehs-mobile-app\android\app\build\intermediates\pre-dexed\debug\classes_899969e6d099b8ea763ba3808e7a1fd766d2778c.jar C:\Users\eakhmas\src\ehs-mobile-app\android\app\build\intermediates\pre-dexed\debug\classes_b721ca6ca0da6054892672e80934d795fcb4c0d8.jar C:\Users\eakhmas\src\ehs-mobile-app\android\app\build\intermediates\pre-dexed\debug\classes_9be34c38e83c262740ce79e80187e0a97e7c76c8.jar C:\Users\eakhmas\src\ehs-mobile-app\android\app\build\intermediates\pre-dexed\debug\classes_4cc21dc8f1d41e512a3b15b31c7384278c35ea16.jar C:\Users\eakhmas\src\ehs-mobile-app\android\app\build\intermediates\pre-dexed\debug\classes_8443a1d229f534e9bdb905d9a7c4650dfcd0e2cb.jar C:\Users\eakhmas\src\ehs-mobile-app\android\app\build\intermediates\pre-dexed\debug\common-1.0.0_52e55260f7ff638cf5b4c52a3d4ecd72ff2b68c5.jar C:\Users\eakhmas\src\ehs-mobile-app\android\app\build\intermediates\pre-dexed\debug\classes_a094409875a8e375b4bdabde5b620352f56be934.jar C:\Users\eakhmas\src\ehs-mobile-app\android\app\build\intermediates\pre-dexed\debug\support-annotations-26.1.0_49ec6fb643d88a30429e0bf8cc1110f4187f2f7c.jar C:\Users\eakhmas\src\ehs-mobile-app\android\app\build\intermediates\pre-dexed\debug\classes_ae8cb9e283b6addced9a76225a4481dfeaee5c44.jar C:\Users\eakhmas\src\ehs-mobile-app\android\app\build\intermediates\pre-dexed\debug\okhttp-urlconnection-3.6.0_c9d5d04c72d6ed3cbcbec488ff7ee5a2733c6e64.jar C:\Users\eakhmas\src\ehs-mobile-app\android\app\build\intermediates\pre-dexed\debug\classes_6dfedd19702fecc126e9b53000c18d857a6e0d5c.jar C:\Users\eakhmas\src\ehs-mobile-app\android\app\build\intermediates\pre-dexed\debug\classes_8ee3a350c343b0219510f84fdd0023533be789eb.jar C:\Users\eakhmas\src\ehs-mobile-app\android\app\build\intermediates\pre-dexed\debug\classes_02e3d720fdb82b20e5aa7428e558dd7bf8b6f44f.jar C:\Users\eakhmas\src\ehs-mobile-app\android\app\build\intermediates\pre-dexed\debug\jsr305-3.0.0_a4be36913eb9d325c86bf6a1b3098e15106ab59d.jar C:\Users\eakhmas\src\ehs-mobile-app\android\app\build\intermediates\pre-dexed\debug\common-1.0.0_28a97a7622ff8f9b0cca855243ae6d38088c377e.jar C:\Users\eakhmas\src\ehs-mobile-app\android\app\build\intermediates\pre-dexed\debug\classes_6cbdd997c40c58178631de6f736c148cd944033f.jar C:\Users\eakhmas\src\ehs-mobile-app\android\app\build\intermediates\pre-dexed\debug\classes_955a1486e9d329cd6ff1f7ba64e5712405b680f0.jar C:\Users\eakhmas\src\ehs-mobile-app\android\app\build\intermediates\pre-dexed\debug\okio-1.13.0_43a3727954feabd0cb289cfb1a6275d02f742616.jar C:\Users\eakhmas\src\ehs-mobile-app\android\app\build\intermediates\pre-dexed\debug\classes_e604738ac5ee164fbf1cc8194ac891817d7629db.jar C:\Users\eakhmas\src\ehs-mobile-app\android\app\build\intermediates\pre-dexed\debug\classes_1b146f1c1b758f1d3048df22b41ea4f01d14bb9f.jar C:\Users\eakhmas\src\ehs-mobile-app\android\app\build\intermediates\pre-dexed\debug\staticlayout-proxy-1.0_629010e9b49b87eb3b868c71f6b1ed2f650b3f06.jar C:\Users\eakhmas\src\ehs-mobile-app\android\app\build\intermediates\pre-dexed\debug\classes_0c56c37ce4586048238bf0d6a713a9d535becd91.jar C:\Users\eakhmas\src\ehs-mobile-app\android\app\build\intermediates\pre-dexed\debug\classes_16a349b068d84d062e622cef5131e670e6bbfc69.jar C:\Users\eakhmas\src\ehs-mobile-app\android\app\build\intermediates\pre-dexed\debug\classes_225bf35343947bbb02243f47c275f0e818e47b4d.jar C:\Users\eakhmas\src\ehs-mobile-app\android\app\build\intermediates\pre-dexed\debug\classes_911a99756a2506bce883e6a852c2699bf3d26d47.jar C:\Users\eakhmas\src\ehs-mobile-app\android\app\build\intermediates\pre-dexed\debug\classes_4a5530546ee89d9e9b9ca6156857f9df7786484b.jar C:\Users\eakhmas\src\ehs-mobile-app\android\app\build\intermediates\pre-dexed\debug\classes_ac6a27b5609bdd6d8e10bb5cd9ef5472d87d4c88.jar C:\Users\eakhmas\src\ehs-mobile-app\android\app\build\intermediates\pre-dexed\debug\okhttp-3.6.0_bc10fb7a41ba174bd6510ed2632992e096a41cdc.jar}



--------------------------------------------------

**Comment by faelsolucoes** [comment]
I have igual problem. You managed to solve ?

**Comment by jkasten2** [comment]
@policz Can you add the following to the very top (line 1) of your `android/app/build.gradle`?
```gradle
buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/'}
    }
    dependencies {
        classpath 'gradle.plugin.com.onesignal:onesignal-gradle-plugin:[0.11.0, 0.99.99]'
    }
}
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'
```

This plugin will align all gms versions in your project to match which will fix any related `Multiple dex files define` errors.

**Comment by SalviShahzad** [comment]
I had the same issue as @policz . Thanks @jkasten2 your solution fixed it.

**Comment by luongs3** [comment]
got this error once, resolved it.
and now, got this error again.
but don't remember how i revolve.
poor me

**Comment by policz** [comment]
Thank you @jkasten2 , 

When i run the same project in Macbook, there is an issue saying that "app has stopped working" in android simulator and even in android device.

can you please me on this issue, Thank you

**Comment by jkasten2** [comment]
@policz Can you include the crash from the logcat of the emulator? The other files you posted will still be helpful depending what the stack trace ends up being.

**Comment by policz** [comment]
hey @jkasten2   , i dont know what is this logcat of the emulator? is it a file somewhere included in app folder?

**Comment by jkasten2** [comment]
@policz It is a log from the device / emulator itself, you can use `adb` or Android Studio to get it. See this guide
https://documentation.onesignal.com/docs/troubleshooting-android#section-how-to-get-a-crash-or-error-log-from-an-android-device

**Comment by policz** [comment]
Hello @jkasten2 , please find the logcat file from the Android Studio when i run the app in android emulator.

[crash.txt](https://github.com/geektimecoil/react-native-onesignal/files/1891530/crash.txt)

**Comment by policz** [comment]
Hello @jkasten2 , please find the logcat file from the Android Studio when i run the app in android emulator.

"Just to remind you that the application is running well in both emulator and physical device when i launch from windows " .

[crash.txt](https://github.com/geektimecoil/react-native-onesignal/files/1891603/crash.txt)

**Comment by jkasten2** [comment]
@policz The crash is from the following in your log.
```java
04-09 19:25:20.566 5004-5004/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ehs, PID: 5004
    java.lang.NoSuchMethodError: No static method isDeviceProtectedStorage(Landroid/content/Context;)Z in class Landroid/support/v4/content/ContextCompat; or its super classes (declaration of 'android.support.v4.content.ContextCompat' appears in /data/app/com.ehs-2b5vMFAJjHpJzno1HWwPdg==/base.apk)
        at com.google.firebase.FirebaseApp.zza(Unknown Source:2)
        at com.google.firebase.FirebaseApp.initializeApp(Unknown Source:115)
        at com.google.firebase.FirebaseApp.initializeApp(Unknown Source:2)
        at com.google.firebase.FirebaseApp.initializeApp(Unknown Source:31)
        at com.google.firebase.provider.FirebaseInitProvider.onCreate(Unknown Source:4)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1917)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:1892)
        at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source:23)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6239)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:5805)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5722)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

It looks like this is due to a version of `android.support.v4` either to old or to new for `com.google.firebase` to use.

Make sure you are using the latest react native OneSignal SDK 3.1.4.

You can also try updating line 2 in your `android-app-build.gradle` from version `0.8.1` to `0.8.2` to see if this fixes the issue. We are working on a new release of [OneSignal-Gradle-Plugin](https://github.com/OneSignal/OneSignal-Gradle-Plugin) this week which should fix the issue if that version does not help.

Also if you want to try to find and fix the mis matched version manually you can get a dependency graph with the following command.
```
./gradlew app:dependencies --info
```

**Comment by policz** [comment]
Thank you @jkasten2 

Yes, i tried with 0.8.2 but still throwing the same issue "app stopped working".
But why the app is not working when its launched from Mac OS

**Comment by policz** [comment]
Actually my android-app-build.gradle contains 
plugins {
    id 'com.onesignal.androidsdk.onesignal-gradle-plugin' version '0.8.1'
}
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

i just removed it and made some changes in the android-app-build.gradle file, Please find the attachment below.

[android-app-build.gradle.txt](https://github.com/geektimecoil/react-native-onesignal/files/1891745/android-app-build.gradle.txt)

**Comment by policz** [comment]
Actually my android-app-build.gradle contains
plugins {
id 'com.onesignal.androidsdk.onesignal-gradle-plugin' version '0.8.1'
}
apply plugin: 'com.onesignal.androidsdk.onesignal-gradle-plugin'

i just removed it and made some changes in the android-app-build.gradle file, Please find the attachment below, and it worked now
[android-app-build.gradle.txt](https://github.com/geektimecoil/react-native-onesignal/files/1891747/android-app-build.gradle.txt)

**Comment by jkasten2** [comment]
@policz Most likely different react native versions of your libraries are being used on one system vs the other. You can double check your project's `package.json` to confirm this.

It could also be due to gradle resolving different versions due to other factors. You would have to run this to see what your getting here
`./gradlew app:dependencies --info`

Note sure if those changes will help or not, again the above gradle command will help tell what the final versions are.

**Comment by policz** [comment]
@jkasten2  i have executed  "./gradlew app:dependencies --info" on my project folder but it says ""No such file or directory"

**Comment by faelsolucoes** [comment]
Hi guys,
I had the issue of first post and I solved without plugins, only run the following steps in android:

1) File app/build.gradle
   I removed in all packages of use "com.google.android.gms", I needed look at all packages used in Project.
For example:
   compile (project(':RNAdMob')) {
        exclude group: 'com.google.android.gms', module: 'play-services-ads'
   }
   compile (project(':react-native-camera')) {
        exclude group: 'com.google.android.gms', module: 'play-services-vision'
   }
   compile (project(':react-native-push-notification')) {
        exclude group: 'com.google.android.gms', module: 'play-services-gcm'
   }

2) Next I added theses packages again
For example:
    compile 'com.google.android.gms:play-services-gcm:11.8.0'
    compile 'com.google.android.gms:play-services-vision:11.8.0'
    compile 'com.google.android.gms:play-services-ads:11.8.0'

3) I fixed version 'com.google.android.gms' 11.8.0 in all packages, because in 12.0.0 I had a problem. I force this version in file build.gradle:
For example:
def googlePlayServicesVersion = '11.8.0'

allprojects {
    repositories {
    .....
    configurations.all {
            resolutionStrategy {
                force "com.google.android.gms:play-services-gcm:$googlePlayServicesVersion"
                force "com.google.android.gms:play-services-vision:$googlePlayServicesVersion"
                force "com.google.android.gms:play-services-ads:$googlePlayServicesVersion"
            }
        } 
    .....
}

4) I fixed in all packages 'com.android.support' the version 27.1.0 in the file app/build.gradle:
For example:
configurations.all {
        resolutionStrategy.eachDependency { DependencyResolveDetails details ->
            def requested = details.requested
            if (requested.group == 'com.android.support') {
                if (!requested.name.startsWith("multidex")) {
                    details.useVersion '27.1.0'
                }
            }
        }
    }

5) In file app/build.gradle I used attribute "multiDexEnabled true" in defaultConfig.

Well, I hope had to help. It's Works for me.

**Comment by blackorchidzvt** [comment]
Follow the ways of @jkasten2 you will solve your problem.
Thanks you @jkasten2

**Comment by nineto4** [comment]
Follow the ways of @jkasten2 you will solve your problem.
Thanks you @jkasten2

**Comment by Gurjap** [comment]
> Firebase Android SDKs now have independent version numbers, allowing
> for more frequent, flexible updates.

Update all your Firebase dependencies to the latest version (as of 2 May 2018):

     Firebase Core          com.google.firebase:firebase-core:15.0.2
        Ads                 com.google.firebase:firebase-ads:15.0.0
      Analytics             com.google.firebase:firebase-analytics:15.0.2
     App Indexing           com.google.firebase:firebase-appindexing:15.0.0
     Authentication         com.google.firebase:firebase-auth:15.1.0
    Cloud Firestore         com.google.firebase:firebase-firestore:16.0.0
    Cloud Functions         com.google.firebase:firebase-functions:15.0.0
    Cloud Messaging         com.google.firebase:firebase-messaging:15.0.2
    Cloud Storage           com.google.firebase:firebase-storage:15.0.2
    Crash Reporting         com.google.firebase:firebase-crash:15.0.2
    Crashlytics             com.crashlytics.sdk.android:crashlytics:2.9.1
    Invites                 com.google.firebase:firebase-invites:15.0.2
    Performance Monitoring  com.google.firebase:firebase-perf:15.1.0
    Realtime Database       com.google.firebase:firebase-database:15.0.0
    Remote Config           com.google.firebase:firebase-config:15.0.2

Release note: https://firebase.google.com/support/release-notes/android

**Comment by Frantch** [comment]
Then I get this error

> > Task :app:processDebugGoogleServices
> Found com.google.android.gms:play-services-maps:15.0.0, but version 15.0.2 is needed for the google-services plugin.

**Comment by Zenntro** [comment]
@Frantch in your case may be just adding in your android/app/build.gradle
dependencies {
     compile 'com.google.android.gms:play-services-maps:15.0.2'
     ...
}

and make sure you have:
apply plugin: 'com.google.gms.google-services'
at the bottom of the same file

**Comment by merbin2012** [comment]
I have the same problem after update the plugins
I am getting this error **"Multiple dex files define Lcom/google/android/gms/internal/measurement/zzeg;
"**
```
    compile "com.google.firebase:firebase-core:+"
    compile "com.google.firebase:firebase-messaging:+"
    compile "com.google.firebase:firebase-config:+"
    compile "com.google.firebase:firebase-perf:+"

    compile "com.google.android.gms:play-services-ads:+"
    compile "com.google.android.gms:play-services-tagmanager:+"
```

**Comment by isacoskun** [comment]
Find the current versions of the libraries you use on Google and add them to your project (build gradle folder). Using + as possible. For example; compile com.firebase: firebase: + or 16. +

Add the latest version of all libraries you use. It will be fixed if there is no other problem. Don't forget to clean and rebuild the project.

**Comment by merbin2012** [comment]
@isacoskun Can you please write full code?

**Comment by jkasten2** [comment]
@merbin2012 @isacoskun I have updated my https://github.com/geektimecoil/react-native-onesignal/issues/20#issuecomment-213542267 reply to recommend using [OneSignal-Gradle-Plugin](https://github.com/OneSignal/OneSignal-Gradle-Plugin) instead of adding these dependencies with `+` versions.
